// feat/help-system commit 6 - the glossary (chapter 13). Every entry
// links to the topic that actually covers it in depth, and every term
// used here also appears in that topic's own body text (checked by
// this task's own consistency test) - a glossary that drifts from the
// chapters it summarizes is worse than no glossary at all.

import type { HelpGlossaryEntry } from './HelpTypes';

export const HELP_GLOSSARY: HelpGlossaryEntry[] = [
  { term: { pl: 'Adres kanalu', en: 'Channel address' }, definition: { pl: 'Tekstowy adres w formacie KARTA.RODZAJ.KANAL wskazujacy fizyczny kanal wejscia/wyjscia, np. ELA1.DI.12.', en: 'A text address in CARD.KIND.CHANNEL format pointing at a physical I/O channel, e.g. ELA1.DI.12.' }, topicId: 'reg-addressing' },
  { term: { pl: 'Aparat', en: 'Device' }, definition: { pl: 'Jednostka konfiguracji zdefiniowana raz w Liscie aparatow; symbol na ekranie tylko wskazuje na nia po identyfikatorze.', en: 'A unit of configuration defined once in the Device List; a screen symbol only points at it by id.' }, topicId: 'dev-why-not-in-screen' },
  { term: { pl: 'Dioda sygnalizacyjna', en: 'Indicator diode' }, definition: { pl: 'Symbol z trzema dopuszczalnymi stanami: ON, OFF i QUALITY.', en: 'A symbol with three allowed states: ON, OFF and QUALITY.' }, topicId: 'elem-indicator-diode' },
  { term: { pl: 'EPW-Logic-Studio', en: 'EPW-Logic-Studio' }, definition: { pl: 'Aplikacja platformy EPW budujaca automatyke: regoly sterowania, blokady i sekwencje.', en: 'The EPW platform application that builds automation: control rules, interlocks and sequences.' }, topicId: 'intro-platform' },
  { term: { pl: 'EPW-OS', en: 'EPW-OS' }, definition: { pl: 'Aplikacja uruchomieniowa platformy EPW - wyswietla ekrany i pracuje na prawdziwym sprzecie.', en: 'The EPW platform\'s runtime application - displays screens and works against real hardware.' }, topicId: 'intro-platform' },
  { term: { pl: 'Historia cofniec', en: 'Undo history' }, definition: { pl: 'Ciag migawek stanu rysunku, po jednej na kazde zapisane dzialanie, z limitem 100 wpisow.', en: 'A sequence of drawing-state snapshots, one per saved action, capped at 100 entries.' }, topicId: 'edit-undo-redo' },
  { term: { pl: 'Home Assistant', en: 'Home Assistant' }, definition: { pl: 'Warstwa dodatkowa (podglad/powiadomienia przez pole publishToHa), nigdy tor sterowania.', en: 'An additional layer (monitoring/notifications via the publishToHa field), never a control path.' }, topicId: 'intro-platform' },
  { term: { pl: 'Identyfikator (id)', en: 'Id' }, definition: { pl: 'Niezmienny klucz maszynowy aparatu, np. KOT_KMG1 - lokalizacja jest z niego wyliczana.', en: 'A device\'s immutable machine key, e.g. KOT_KMG1 - its location is derived from it.' }, topicId: 'dev-naming' },
  { term: { pl: 'Kafel', en: 'Tile' }, definition: { pl: 'Jedna komorka siatki ekranu planu, odpowiadajaca 8 metrom w rzeczywistosci.', en: 'One grid cell of the plan screen, corresponding to 8 real-world meters.' }, topicId: 'plan-projection-grid' },
  { term: { pl: 'Kanal', en: 'Channel' }, definition: { pl: 'Pojedyncze wejscie albo wyjscie na karcie, numerowane od 1.', en: 'A single input or output on a card, numbered starting from 1.' }, topicId: 'reg-cards' },
  { term: { pl: 'Karta', en: 'Card' }, definition: { pl: 'Rejestrowa reprezentacja fizycznej karty I/O sterownika: identyfikator, rodzaj kanalow, ich liczba.', en: 'The registry\'s representation of a physical controller I/O card: an id, a channel kind, a channel count.' }, topicId: 'reg-cards' },
  { term: { pl: 'Kolizja kanalow', en: 'Channel collision' }, definition: { pl: 'Sytuacja, gdy dwa aparaty wskazuja na ten sam fizyczny kanal - wykrywana i sygnalizowana przy zapisie.', en: 'Two devices pointing at the same physical channel - detected and flagged on save.' }, topicId: 'dev-form-validation' },
  { term: { pl: 'Kropka wezlowa', en: 'Junction dot' }, definition: { pl: 'Znacznik w punkcie siatki, gdzie spotykaja sie trzy lub wiecej galezi przewodow/zaciskow.', en: 'A marker at a grid point where three or more wire/terminal branches meet.' }, topicId: 'sch-junction-dot' },
  { term: { pl: 'Licznik przelaczen', en: 'Switch counter' }, definition: { pl: 'Opcjonalne zliczanie przelaczen aparatu SWITCHED (sygnal .COUNTER) - bez wbudowanego progu ostrzegawczego.', en: 'Optional counting of a SWITCHED device\'s operations (the .COUNTER signal) - with no built-in warning threshold.' }, topicId: 'dev-switched' },
  { term: { pl: 'Lokalizacja', en: 'Location' }, definition: { pl: 'Krotki, wielkoliterowy przedrostek identyfikatora aparatu, np. KOT.', en: 'A short, uppercase prefix of a device id, e.g. KOT.' }, topicId: 'reg-locations' },
  { term: { pl: 'Migracja', en: 'Migration' }, definition: { pl: 'Automatyczne przeksztalcenie starszego pliku projektu do biezacego ksztaltu przy wczytaniu.', en: 'The automatic reshaping of an older project file into the current shape on load.' }, topicId: 'file-versioning' },
  { term: { pl: 'Miernik', en: 'Meter' }, definition: { pl: 'Dynamiczny element ekranu zlozony z wierszy pomiarowych, o wysokosci wyliczanej automatycznie.', en: 'A dynamic screen element built from measurement rows, with its height always computed.' }, topicId: 'elem-meter' },
  { term: { pl: 'Obrot', en: 'Rotation' }, definition: { pl: 'Pole obiektu planu (0/90/180/270 stopni) - obroty 180/270 dostepne tylko gdy sprite ma wlasny widok tylny w manifescie.', en: 'A plan object field (0/90/180/270 degrees) - rotations 180/270 are only available when the sprite has its own rear view in the manifest.' }, topicId: 'plan-rotation' },
  { term: { pl: 'Osrodek', en: 'Medium' }, definition: { pl: 'Jeden z trzech rodzajow instalacji, do ktorego nalezy przewod: prad, woda albo wentylacja.', en: 'One of the three installation kinds a wire belongs to: electrical, water or ventilation.' }, topicId: 'sch-media' },
  { term: { pl: 'Oznaczenie', en: 'Designation' }, definition: { pl: 'To, co widac na schemacie przy symbolu, np. -K1 - odrebne od identyfikatora aparatu.', en: 'What is shown on the diagram next to a symbol, e.g. -K1 - distinct from the device id.' }, topicId: 'dev-naming' },
  { term: { pl: 'Panel sygnalizacyjny', en: 'Signal panel' }, definition: { pl: 'Dynamiczny element ekranu jak miernik, ale kazdy wiersz konczy sie dioda dwustanowa.', en: 'A dynamic screen element like the meter, but every row ends in a two-state diode.' }, topicId: 'elem-signal-panel' },
  { term: { pl: 'Plik projektu', en: 'Project file' }, definition: { pl: 'Plik .epwsyn (JSON, format EPW_SYNOPTIC) zawierajacy caly stan projektu.', en: 'The .epwsyn file (JSON, EPW_SYNOPTIC format) holding the whole project state.' }, topicId: 'file-contents' },
  { term: { pl: 'Podglad edytora', en: 'Editor preview' }, definition: { pl: 'Recznie ustawiony stan pokazywany na symbolu podczas projektowania - nigdy odczyt z prawdziwego sprzetu.', en: 'A manually set state shown on a symbol while designing - never a reading from real hardware.' }, topicId: 'sym-states-preview' },
  { term: { pl: 'Punkt graniczny', en: 'Boundary point' }, definition: { pl: 'Symbol reprezentujacy miejsce, w ktorym instalacja laczy sie ze swiatem zewnetrznym - zrodlo albo odplyw.', en: 'A symbol representing where the installation meets the outside world - a source or a sink.' }, topicId: 'sch-boundary-point' },
  { term: { pl: 'Ramka', en: 'Frame' }, definition: { pl: 'Czysta grafika ilustrujaca szafe, pomieszczenie albo strefe - bez zaciskow i bez pola Aparat.', en: 'Pure graphics illustrating a cabinet, room or zone - no terminals and no Aparat field.' }, topicId: 'elem-frame-building' },
  { term: { pl: 'Rejestr', en: 'Registry' }, definition: { pl: 'Wspolna lista projektu (lokalizacje, karty albo aparaty), z ktorej ekran tylko czerpie przez odwolania.', en: 'A project-wide list (locations, cards or devices) the screen only draws references from.' }, topicId: 'reg-locations' },
  { term: { pl: 'Rozbieznosc', en: 'Discrepancy' }, definition: { pl: 'Sytuacja, gdy polecenie wyslane do aparatu SWITCHED nie zostalo potwierdzone przez wejscie zwrotne w ustalonym czasie.', en: 'A command sent to a SWITCHED device that feedback did not confirm within the configured time.' }, topicId: 'dev-switched' },
  { term: { pl: 'Rzut izometryczny', en: 'Isometric projection' }, definition: { pl: 'Dimetryczny rzut 2:1 uzywany na ekranie planu do pokazania dzialki z gory pod katem.', en: 'The 2:1 dimetric view the plan screen uses to show the plot from an angled overhead perspective.' }, topicId: 'plan-projection-grid' },
  { term: { pl: 'Sprzezenie zwrotne', en: 'Feedback' }, definition: { pl: 'Wejscie (albo dwa) potwierdzajace rzeczywisty stan aparatu SWITCHED - tryb DUAL, SINGLE albo NONE.', en: 'An input (or two) confirming a SWITCHED device\'s actual state - mode DUAL, SINGLE or NONE.' }, topicId: 'dev-switched' },
  { term: { pl: 'Stan bezpieczny', en: 'Safe state' }, definition: { pl: 'Zachowanie aparatu zdefiniowane na wypadek startu albo utraty lacznosci - nalezy do sprzetu, nie do ekranu.', en: 'A device\'s defined behavior on startup or link loss - belongs to the hardware, not to the screen.' }, topicId: 'dev-switched' },
  { term: { pl: 'Sygnal zakazu', en: 'Inhibit signal' }, definition: { pl: 'Sygnal pozwalajacy logice ZABRONIC wykonania polecenia, nie tylko je wyslac.', en: 'A signal letting logic FORBID a command from executing, not only send one.' }, topicId: 'dev-signals-commands' },
  { term: { pl: 'Szyna zbiorcza', en: 'Busbar' }, definition: { pl: 'Przewod w stylu BUS, wizualnie grubszy, przeznaczony do podlaczania wielu odbiorow na calej dlugosci.', en: 'A wire in BUS style, drawn thicker, meant to have many loads tapped along its whole length.' }, topicId: 'sch-wire-style' },
  { term: { pl: 'Walidacja na zywo', en: 'Live validation' }, definition: { pl: 'Sprawdzanie formularza aparatu przy kazdej zmianie pola, blokujace Zapisz dopoki istnieje blad.', en: 'Checking the device form on every field change, withholding Save while an error exists.' }, topicId: 'dev-form-validation' },
  { term: { pl: 'Wersja schematu', en: 'Schema version' }, definition: { pl: 'Numer w pliku projektu rosnacy wylacznie przy zmianie niezgodnej wstecz.', en: 'A number in the project file that only increases on a backward-incompatible change.' }, topicId: 'file-versioning' },
  { term: { pl: 'Wezel', en: 'Node' }, definition: { pl: 'Punkt siatki, w ktorym przewody i zaciski moga sie geometrycznie stykac, tworzac jedna siec.', en: 'A grid point where wires and terminals can geometrically touch, forming one net.' }, topicId: 'sch-node-model' },
  { term: { pl: 'Wymiar w kaflach', en: 'Footprint' }, definition: { pl: 'Ile kafli zajmuje obiekt planu - odczytywane z manifestu sprite\'ow, nie ustawiane recznie.', en: 'How many tiles a plan object occupies - read from the sprite manifest, never set by hand.' }, topicId: 'plan-placing-objects' },
  { term: { pl: 'Zachowanie', en: 'Behavior' }, definition: { pl: 'To, co klasyfikuje aparat: SWITCHED, SIGNAL, MEASURED albo MODULATED - nie jego rodzaj opisowy.', en: 'What classifies a device: SWITCHED, SIGNAL, MEASURED or MODULATED - not its descriptive kind.' }, topicId: 'dev-behavior-classification' },
  { term: { pl: 'Zacisk', en: 'Terminal' }, definition: { pl: 'Punkt symbolu, w ktorym moze sie z nim stykac przewod - zawsze na srodku jednej z czterech krawedzi.', en: 'A point on a symbol where a wire can touch it - always at the middle of one of its four edges.' }, topicId: 'sym-terminals' },
];
